// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    $('#login').click(function() {
      return $('.login-form').slideDown("slow");
    });
    return $(document).click(function(e) {
      if (e.target.id !== 'login') {
        return $('.login-form').slideUp("slow");
      }
    });
  });

}).call(this);
