// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var pass;

    $('#register input[type="button"]').click(function() {
      var email, pass, pass_conf, password, username;

      username = $('#register input[name="user"]');
      email = $('#register input[name="email"]');
      password = $('#register input[name="pass"]');
      pass_conf = $('#register input[name="pass_conf"]');
      return pass = true;
    }, !/^([\w_-]{4,15})$/.test(username.val()) ? (username.addClass('error'), username.popover({
      'placement': 'right',
      'trigger': 'manual',
      'title': user_not_valid_title,
      'content': user_not_valid
    }), username.popover('show'), pass = false) : void 0);
    $('#login input[type="button"]').click(function() {
      return alert('login');
    });
    return $('#register input[name="user"], #register input[name="email"], #register input[name="pass"],\
		#register input[name="pass_conf"], #login input[name="user"], #login input[name="pass"]').focus(function() {
      $(this).removeClass('error');
      return $(this).popover('hide');
    });
  });

}).call(this);
